# Generated by Django 4.1.7 on 2023-06-07 16:42

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movie_photo_ticket_updated_at_alter_news_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tg_owner_id',
            field=models.IntegerField(null=True, verbose_name='Tg_user_id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=19, null=True, validators=[myapp.models.validate_uzb_phone], verbose_name='Phone'),
        ),
    ]
