# Generated by Django 4.1.7 on 2023-06-07 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_news_title_ticket_tg_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tg_owner_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tg_user_id'),
        ),
    ]
